# !Automatically generated from ./functions.def - DO NOT EDIT!
/bcmp/ { printf "bcmp.o " }
/bcopy/ { printf "bcopy.o " }
/bzero/ { printf "bzero.o " }
/clock/ { printf "clock.o " }
/getopt/ { printf "getopt.o " }
/getpagesize/ { printf "getpagesize.o " }
/getcwd/ { printf "getcwd.o " }
/index/ { printf "index.o " }
/insque/ { printf "insque.o " }
/memchr/ { printf "memchr.o " }
/memcmp/ { printf "memcmp.o " }
/memcpy/ { printf "memcpy.o " }
/memmove/ { printf "memmove.o " }
/memset/ { printf "memset.o " }
/random/ { printf "random.o " }
/rename/ { printf "rename.o " }
/rindex/ { printf "rindex.o " }
/strcasecmp/ { printf "strcasecmp.o " }
/strncasecmp/ { printf "strncasecmp.o " }
/strchr/ { printf "strchr.o " }
/strdup/ { printf "strdup.o " }
/strrchr/ { printf "strrchr.o " }
/strstr/ { printf "strstr.o " }
/strtod/ { printf "strtod.o " }
/strtol/ { printf "strtol.o " }
/strtoul/ { printf "strtoul.o " }
/tmpnam/ { printf "tmpnam.o " }
/vfork/ { printf "vfork.o " }
/vfprintf/ { printf "vfprintf.o " }
/vprintf/ { printf "vprintf.o " }
/vsprintf/ { printf "vsprintf.o " }
/sigsetmask/ { printf "sigsetmask.o " }
/alloca/ { printf "alloca.o " }
/waitpid/ { printf "waitpid.o " }
