/* This file is is generated by a shell script.  DO NOT EDIT! */

/* emulate the original gld for the given sslittle
   Copyright (C) 1991, 1993 Free Software Foundation, Inc.
   Written by Steve Chamberlain steve@cygnus.com

This file is part of GLD, the Gnu Linker.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  */

#define TARGET_IS_sslittle

#include "bfd.h"
#include "sysdep.h"
#include "bfdlink.h"

#include "ld.h"
#include "config.h"
#include "ldmain.h"
#include "ldemul.h"
#include "ldfile.h"
#include "ldmisc.h"

static void gldsslittle_before_parse PARAMS ((void));
static char *gldsslittle_get_script PARAMS ((int *isfile));

static void
gldsslittle_before_parse()
{
#ifndef TARGET_			/* I.e., if not generic.  */
  ldfile_output_architecture = bfd_arch_ss;
#endif /* not TARGET_ */
}

static char *
gldsslittle_get_script(isfile)
     int *isfile;
{			     
  *isfile = 0;

  if (link_info.relocateable == true && config.build_constructors == true)
    return
  ; else if (link_info.relocateable == true) return
  ; else if (!config.text_read_only) return
  ; else if (!config.magic_demand_paged) return
  ; else return
; }

struct ld_emulation_xfer_struct ld_sslittle_emulation = 
{
  gldsslittle_before_parse,
  syslib_default,
  hll_default,
  after_parse_default,
  after_allocation_default,
  set_output_arch_default,
  ldemul_default_target,
  before_allocation_default,
  gldsslittle_get_script,
  "sslittle",
  "ss-coff-little"
};
